name: gnss_acg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - xarray
  - matplotlib
  - statsmodels
  - pip:
    - git+https://github.com/BioM2-Lab/gnssvod.git
    - jupyterlab
    - ipykernel
    - georinex
    - qgrid
